<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXtoY.php Add Role Group
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\addRoleToGroup;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository;
use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository;

final class AddRoleToGroup
{
    private $bus;

    public function __construct(RoleRepository $role, GroupRepository $group)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\addRoleToGroup\AddRoleToGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\addRoleToGroup\AddRoleToGroupCommandHandler');
        }

    public function addRoleToGroup($roleId, $groupId)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\addRoleToGroup\AddRoleToGroupCommand',
        [
            "roleId" => $roleId,
            "groupId" => $groupId
        ], []);
    }
}
