<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXtoY.php Add Module Role
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\addModuleToRole;

use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository;
use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository;

final class AddModuleToRole
{
    private $bus;

    public function __construct(ModuleRepository $module, RoleRepository $role)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\addModuleToRole\AddModuleToRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\addModuleToRole\AddModuleToRoleCommandHandler');
        }

    public function addModuleToRole($moduleId, $roleId)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\addModuleToRole\AddModuleToRoleCommand',
        [
            "moduleId" => $moduleId,
            "roleId" => $roleId
        ], []);
    }
}
