<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Delete Role id
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\delete;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository; // TODO first use must be the Repository


final class DeleteRole
{
    private $bus;

    public function __construct(RoleRepository $role){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\delete\DeleteRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\delete\DeleteRoleCommandHandler');
}

    public function delete($id)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\delete\DeleteRoleCommand',
        [
                'id' => $id
        ], []);
    }
}
