<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXtoY.php Add Role Module
 */
namespace ProyectoTAU\TAU\Module\Administration\Module\Application\addRoleToModule;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository;
use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository;

final class AddRoleToModule
{
    private $bus;

    public function __construct(RoleRepository $role, ModuleRepository $module)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Module\Application\addRoleToModule\AddRoleToModuleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Module\Application\addRoleToModule\AddRoleToModuleCommandHandler');
        }

    public function addRoleToModule($roleId, $moduleId)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Module\Application\addRoleToModule\AddRoleToModuleCommand',
        [
            "roleId" => $roleId,
            "moduleId" => $moduleId
        ], []);
    }
}
