<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Read Module id
 */
namespace ProyectoTAU\TAU\Module\Administration\Module\Application\read;

use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository; // TODO first use must be the Repository
use ProyectoTAU\TAU\Module\Administration\Module\Domain\Module;

final class ReadModule
{
    private $bus;

    public function __construct(ModuleRepository $module){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Module\Application\read\ReadModuleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Module\Application\read\ReadModuleCommandHandler');
}

    public function read($id): Module
    {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Module\Application\read\ReadModuleCommand',
        [
                'id' => $id
        ], []);
    }
}
