<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Delete Module id
 */
namespace ProyectoTAU\TAU\Module\Administration\Module\Application\delete;

use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository; // TODO first use must be the Repository


final class DeleteModule
{
    private $bus;

    public function __construct(ModuleRepository $module){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Module\Application\delete\DeleteModuleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Module\Application\delete\DeleteModuleCommandHandler');
}

    public function delete($id)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Module\Application\delete\DeleteModuleCommand',
        [
                'id' => $id
        ], []);
    }
}
