<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXtoY.php Add Group User
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\addGroupToUser;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository;
use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository;

final class AddGroupToUser
{
    private $bus;

    public function __construct(GroupRepository $group, UserRepository $user)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\addGroupToUser\AddGroupToUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\addGroupToUser\AddGroupToUserCommandHandler');
        }

    public function addGroupToUser($groupId, $userId)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\addGroupToUser\AddGroupToUserCommand',
        [
            "groupId" => $groupId,
            "userId" => $userId
        ], []);
    }
}
