<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Update User id,name,surname,login
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\update;

use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository; // TODO first use must be the Repository


final class UpdateUser
{
    private $bus;

    public function __construct(UserRepository $user){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\update\UpdateUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\update\UpdateUserCommandHandler');
}

    public function update($id, $name, $surname, $login)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\update\UpdateUserCommand',
        [
                'id' => $id,
                'name' => $name,
                'surname' => $surname,
                'login' => $login
        ], []);
    }
}
