<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php Get Group Role
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\getGroupsFromRole;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository;

final class GetGroupsFromRole
{
    private $bus;

    public function __construct(RoleRepository $role)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\getGroupsFromRole\GetGroupsFromRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\getGroupsFromRole\GetGroupsFromRoleCommandHandler');
        }

    public function getGroupsFromRole($roleId): array {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\getGroupsFromRole\GetGroupsFromRoleCommand',
            [
                "roleId" => $roleId
            ], []);
    }
}
