<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php Get Role Module
 */
namespace ProyectoTAU\TAU\Module\Administration\Module\Application\getRolesFromModule;

use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository;

final class GetRolesFromModule
{
    private $bus;

    public function __construct(ModuleRepository $module)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Module\Application\getRolesFromModule\GetRolesFromModuleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Module\Application\getRolesFromModule\GetRolesFromModuleCommandHandler');
        }

    public function getRolesFromModule($moduleId): array {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Module\Application\getRolesFromModule\GetRolesFromModuleCommand',
            [
                "moduleId" => $moduleId
            ], []);
    }
}
