<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Update Role id,name,desc
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\update;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository; // TODO first use must be the Repository


final class UpdateRole
{
    private $bus;

    public function __construct(RoleRepository $role){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\update\UpdateRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\update\UpdateRoleCommandHandler');
}

    public function update($id, $name, $desc)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\update\UpdateRoleCommand',
        [
                'id' => $id,
                'name' => $name,
                'desc' => $desc
        ], []);
    }
}
