<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Create User id,name,surname,login
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\create;

use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository; // TODO first use must be the Repository


final class CreateUser
{
    private $bus;

    public function __construct(UserRepository $user){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\create\CreateUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\create\CreateUserCommandHandler');
}

    public function create($id, $name, $surname, $login)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\create\CreateUserCommand',
        [
                'id' => $id,
                'name' => $name,
                'surname' => $surname,
                'login' => $login
        ], []);
    }
}
