<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Delete User id
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\delete;

use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository; // TODO first use must be the Repository


final class DeleteUser
{
    private $bus;

    public function __construct(UserRepository $user){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\delete\DeleteUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\delete\DeleteUserCommandHandler');
}

    public function delete($id)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\delete\DeleteUserCommand',
        [
                'id' => $id
        ], []);
    }
}
