<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Create Module id,name,desc
 */
namespace ProyectoTAU\TAU\Module\Administration\Module\Application\create;

use ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository; // TODO first use must be the Repository


final class CreateModule
{
    private $bus;

    public function __construct(ModuleRepository $module){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Module\Domain\ModuleRepository',
            function () use ($module){
                return  $module;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Module\Application\create\CreateModuleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Module\Application\create\CreateModuleCommandHandler');
}

    public function create($id, $name, $desc)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Module\Application\create\CreateModuleCommand',
        [
                'id' => $id,
                'name' => $name,
                'desc' => $desc
        ], []);
    }
}
