<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php Get Group User
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\getGroupsFromUser;

use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository;

final class GetGroupsFromUser
{
    private $bus;

    public function __construct(UserRepository $user)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\getGroupsFromUser\GetGroupsFromUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\getGroupsFromUser\GetGroupsFromUserCommandHandler');
        }

    public function getGroupsFromUser($userId): array {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\getGroupsFromUser\GetGroupsFromUserCommand',
            [
                "userId" => $userId
            ], []);
    }
}
