<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php %Usecase% %EntityX% %EntityY%
 */
namespace ProyectoTAU\TAU\Module\Administration\%EntityY%\Application\%usecase%%EntityX%sFrom%EntityY%;

use ProyectoTAU\TAU\Module\Administration\%EntityY%\Domain\%EntityY%Repository;

final class %Usecase%%EntityX%sFrom%EntityY%
{
    private $bus;

    public function __construct(%EntityY%Repository $%entityY%)
    {
        $this->bus = app('CommandBus');

        app()->bind('%fcer%',
            function () use ($%entityY%){
                return  $%entityY%;
            });

        $this->bus->addHandler('%fcns%\%Usecase%%EntityX%sFrom%EntityY%Command',
                               '%fcns%\%Usecase%%EntityX%sFrom%EntityY%CommandHandler');
        }

    public function %usecase%%EntityX%sFrom%EntityY%($%entityY%Id): array {
        return $this->bus->dispatch('%fcns%\%Usecase%%EntityX%sFrom%EntityY%Command',
            [
                "%entityY%Id" => $%entityY%Id
            ], []);
    }
}
