<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Read Role id
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\read;

use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository; // TODO first use must be the Repository
use ProyectoTAU\TAU\Module\Administration\Role\Domain\Role;

final class ReadRole
{
    private $bus;

    public function __construct(RoleRepository $role){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\read\ReadRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\read\ReadRoleCommandHandler');
}

    public function read($id): Role
    {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\read\ReadRoleCommand',
        [
                'id' => $id
        ], []);
    }
}
