<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Read User id
 */
namespace ProyectoTAU\TAU\Module\Administration\User\Application\read;

use ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository; // TODO first use must be the Repository
use ProyectoTAU\TAU\Module\Administration\User\Domain\User;

final class ReadUser
{
    private $bus;

    public function __construct(UserRepository $user){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\User\Domain\UserRepository',
            function () use ($user){
                return  $user;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\User\Application\read\ReadUserCommand',
                               'ProyectoTAU\TAU\Module\Administration\User\Application\read\ReadUserCommandHandler');
}

    public function read($id): User
    {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\User\Application\read\ReadUserCommand',
        [
                'id' => $id
        ], []);
    }
}
