<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php Get User Group
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\getUsersFromGroup;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository;

final class GetUsersFromGroup
{
    private $bus;

    public function __construct(GroupRepository $group)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\getUsersFromGroup\GetUsersFromGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\getUsersFromGroup\GetUsersFromGroupCommandHandler');
        }

    public function getUsersFromGroup($groupId): array {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\getUsersFromGroup\GetUsersFromGroupCommand',
            [
                "groupId" => $groupId
            ], []);
    }
}
