<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXtoY.php Add Group Role
 */
namespace ProyectoTAU\TAU\Module\Administration\Role\Application\addGroupToRole;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository;
use ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository;

final class AddGroupToRole
{
    private $bus;

    public function __construct(GroupRepository $group, RoleRepository $role)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        app()->bind('ProyectoTAU\TAU\Module\Administration\Role\Domain\RoleRepository',
            function () use ($role){
                return  $role;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Role\Application\addGroupToRole\AddGroupToRoleCommand',
                               'ProyectoTAU\TAU\Module\Administration\Role\Application\addGroupToRole\AddGroupToRoleCommandHandler');
        }

    public function addGroupToRole($groupId, $roleId)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Role\Application\addGroupToRole\AddGroupToRoleCommand',
        [
            "groupId" => $groupId,
            "roleId" => $roleId
        ], []);
    }
}
