<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Update Group id,name,desc
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\update;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository; // TODO first use must be the Repository


final class UpdateGroup
{
    private $bus;

    public function __construct(GroupRepository $group){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\update\UpdateGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\update\UpdateGroupCommandHandler');
}

    public function update($id, $name, $desc)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\update\UpdateGroupCommand',
        [
                'id' => $id,
                'name' => $name,
                'desc' => $desc
        ], []);
    }
}
