<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Delete Group id
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\delete;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository; // TODO first use must be the Repository


final class DeleteGroup
{
    private $bus;

    public function __construct(GroupRepository $group){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\delete\DeleteGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\delete\DeleteGroupCommandHandler');
}

    public function delete($id)
    {
        $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\delete\DeleteGroupCommand',
        [
                'id' => $id
        ], []);
    }
}
