<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseXsFromY.php Get Role Group
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\getRolesFromGroup;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository;

final class GetRolesFromGroup
{
    private $bus;

    public function __construct(GroupRepository $group)
    {
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\getRolesFromGroup\GetRolesFromGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\getRolesFromGroup\GetRolesFromGroupCommandHandler');
        }

    public function getRolesFromGroup($groupId): array {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\getRolesFromGroup\GetRolesFromGroupCommand',
            [
                "groupId" => $groupId
            ], []);
    }
}
