<?php
/*
 * Autogenerated by
 * php tools/makeUseCaseEntity.php Read Group id
 */
namespace ProyectoTAU\TAU\Module\Administration\Group\Application\read;

use ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository; // TODO first use must be the Repository
use ProyectoTAU\TAU\Module\Administration\Group\Domain\Group;

final class ReadGroup
{
    private $bus;

    public function __construct(GroupRepository $group){
        $this->bus = app('Joselfonseca\LaravelTactician\CommandBusInterface');

        app()->bind('ProyectoTAU\TAU\Module\Administration\Group\Domain\GroupRepository',
            function () use ($group){
                return  $group;
            });

        $this->bus->addHandler('ProyectoTAU\TAU\Module\Administration\Group\Application\read\ReadGroupCommand',
                               'ProyectoTAU\TAU\Module\Administration\Group\Application\read\ReadGroupCommandHandler');
}

    public function read($id): Group
    {
        return $this->bus->dispatch('ProyectoTAU\TAU\Module\Administration\Group\Application\read\ReadGroupCommand',
        [
                'id' => $id
        ], []);
    }
}
